"""Added new Column

Revision ID: a73bc6660d6a
Revises: b605706b98d9
Create Date: 2025-03-28 18:52:27.566551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73bc6660d6a'
down_revision = 'b605706b98d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sustainability_info', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sustainability_info')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
